### ISSUE TITLE
pre-trained weight folder is empty

### ISSUE THREAD

**Issue by hyungraelee** [switiz/deepspeech2.pytorch#1]
First of all, thank you for sharing a good project. 😄

The pre-trained weight folder you shared is empty, can you share it again?

**Comment by switiz** [comment]
Thank you for your interest.
Unfortunately, the project is currently no longer in progress and the original learning checkpoints have been lost.
We apologize for not being able to help you.

**Comment by hyungraelee** [comment]
Thank you for checking 😭
